name: GitHub-Profile-3D-Contrib
on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: tegardevINF
      - name: Commit & Push
        run: |
          git config user.email "tegardevINF@gmail.com"
          git config user.name "tegardevINF"
          git stash
          git pull --rebase
          git stash pop
          git add -A .
          git commit -m "chore: regenerate 3D contrib graph" || true
          git push
